package edu.nu.forensic.etw;

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: etwdata.proto

public final class Etwdata {
    private Etwdata() {}
    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }
    public interface EventRecordsOrBuilder extends
            // @@protoc_insertion_point(interface_extends:ETWproto.EventRecords)
            com.google.protobuf.MessageLiteOrBuilder {

        /**
         * <code>repeated .ETWproto.datad data = 1;</code>
         */
        java.util.List<Etwdata.datad>
        getDataList();
        /**
         * <code>repeated .ETWproto.datad data = 1;</code>
         */
        Etwdata.datad getData(int index);
        /**
         * <code>repeated .ETWproto.datad data = 1;</code>
         */
        int getDataCount();

        /**
         * <code>repeated int64 providerID = 4;</code>
         */
        java.util.List<java.lang.Long> getProviderIDList();
        /**
         * <code>repeated int64 providerID = 4;</code>
         */
        int getProviderIDCount();
        /**
         * <code>repeated int64 providerID = 4;</code>
         */
        long getProviderID(int index);

        /**
         * <code>repeated uint32 opcode = 5;</code>
         */
        java.util.List<java.lang.Integer> getOpcodeList();
        /**
         * <code>repeated uint32 opcode = 5;</code>
         */
        int getOpcodeCount();
        /**
         * <code>repeated uint32 opcode = 5;</code>
         */
        int getOpcode(int index);

        /**
         * <code>repeated int32 processID = 6;</code>
         */
        java.util.List<java.lang.Integer> getProcessIDList();
        /**
         * <code>repeated int32 processID = 6;</code>
         */
        int getProcessIDCount();
        /**
         * <code>repeated int32 processID = 6;</code>
         */
        int getProcessID(int index);

        /**
         * <code>repeated int32 threadID = 7;</code>
         */
        java.util.List<java.lang.Integer> getThreadIDList();
        /**
         * <code>repeated int32 threadID = 7;</code>
         */
        int getThreadIDCount();
        /**
         * <code>repeated int32 threadID = 7;</code>
         */
        int getThreadID(int index);

        /**
         * <code>repeated bytes eventName = 8;</code>
         */
        java.util.List<com.google.protobuf.ByteString> getEventNameList();
        /**
         * <code>repeated bytes eventName = 8;</code>
         */
        int getEventNameCount();
        /**
         * <code>repeated bytes eventName = 8;</code>
         */
        com.google.protobuf.ByteString getEventName(int index);

        /**
         * <code>repeated int64 timestamp = 9;</code>
         */
        java.util.List<java.lang.Long> getTimestampList();
        /**
         * <code>repeated int64 timestamp = 9;</code>
         */
        int getTimestampCount();
        /**
         * <code>repeated int64 timestamp = 9;</code>
         */
        long getTimestamp(int index);

        /**
         * <code>repeated bytes callstack = 10;</code>
         */
        java.util.List<com.google.protobuf.ByteString> getCallstackList();
        /**
         * <code>repeated bytes callstack = 10;</code>
         */
        int getCallstackCount();
        /**
         * <code>repeated bytes callstack = 10;</code>
         */
        com.google.protobuf.ByteString getCallstack(int index);
    }
    /**
     * Protobuf type {@code ETWproto.EventRecords}
     */
    public  static final class EventRecords extends
            com.google.protobuf.GeneratedMessageLite<
                    EventRecords, EventRecords.Builder> implements
            // @@protoc_insertion_point(message_implements:ETWproto.EventRecords)
            EventRecordsOrBuilder {
        private EventRecords() {
            data_ = emptyProtobufList();
            providerID_ = emptyLongList();
            opcode_ = emptyIntList();
            processID_ = emptyIntList();
            threadID_ = emptyIntList();
            eventName_ = emptyProtobufList();
            timestamp_ = emptyLongList();
            callstack_ = emptyProtobufList();
        }
        public static final int DATA_FIELD_NUMBER = 1;
        private com.google.protobuf.Internal.ProtobufList<Etwdata.datad> data_;
        /**
         * <code>repeated .ETWproto.datad data = 1;</code>
         */
        public java.util.List<Etwdata.datad> getDataList() {
            return data_;
        }
        /**
         * <code>repeated .ETWproto.datad data = 1;</code>
         */
        public java.util.List<? extends Etwdata.datadOrBuilder>
        getDataOrBuilderList() {
            return data_;
        }
        /**
         * <code>repeated .ETWproto.datad data = 1;</code>
         */
        public int getDataCount() {
            return data_.size();
        }
        /**
         * <code>repeated .ETWproto.datad data = 1;</code>
         */
        public Etwdata.datad getData(int index) {
            return data_.get(index);
        }
        /**
         * <code>repeated .ETWproto.datad data = 1;</code>
         */
        public Etwdata.datadOrBuilder getDataOrBuilder(
                int index) {
            return data_.get(index);
        }
        private void ensureDataIsMutable() {
            if (!data_.isModifiable()) {
                data_ =
                        com.google.protobuf.GeneratedMessageLite.mutableCopy(data_);
            }
        }

        /**
         * <code>repeated .ETWproto.datad data = 1;</code>
         */
        private void setData(
                int index, Etwdata.datad value) {
            if (value == null) {
                throw new NullPointerException();
            }
            ensureDataIsMutable();
            data_.set(index, value);
        }
        /**
         * <code>repeated .ETWproto.datad data = 1;</code>
         */
        private void setData(
                int index, Etwdata.datad.Builder builderForValue) {
            ensureDataIsMutable();
            data_.set(index, builderForValue.build());
        }
        /**
         * <code>repeated .ETWproto.datad data = 1;</code>
         */
        private void addData(Etwdata.datad value) {
            if (value == null) {
                throw new NullPointerException();
            }
            ensureDataIsMutable();
            data_.add(value);
        }
        /**
         * <code>repeated .ETWproto.datad data = 1;</code>
         */
        private void addData(
                int index, Etwdata.datad value) {
            if (value == null) {
                throw new NullPointerException();
            }
            ensureDataIsMutable();
            data_.add(index, value);
        }
        /**
         * <code>repeated .ETWproto.datad data = 1;</code>
         */
        private void addData(
                Etwdata.datad.Builder builderForValue) {
            ensureDataIsMutable();
            data_.add(builderForValue.build());
        }
        /**
         * <code>repeated .ETWproto.datad data = 1;</code>
         */
        private void addData(
                int index, Etwdata.datad.Builder builderForValue) {
            ensureDataIsMutable();
            data_.add(index, builderForValue.build());
        }
        /**
         * <code>repeated .ETWproto.datad data = 1;</code>
         */
        private void addAllData(
                java.lang.Iterable<? extends Etwdata.datad> values) {
            ensureDataIsMutable();
            com.google.protobuf.AbstractMessageLite.addAll(
                    values, data_);
        }
        /**
         * <code>repeated .ETWproto.datad data = 1;</code>
         */
        private void clearData() {
            data_ = emptyProtobufList();
        }
        /**
         * <code>repeated .ETWproto.datad data = 1;</code>
         */
        private void removeData(int index) {
            ensureDataIsMutable();
            data_.remove(index);
        }

        public static final int PROVIDERID_FIELD_NUMBER = 4;
        private com.google.protobuf.Internal.LongList providerID_;
        /**
         * <code>repeated int64 providerID = 4;</code>
         */
        public java.util.List<java.lang.Long>
        getProviderIDList() {
            return providerID_;
        }
        /**
         * <code>repeated int64 providerID = 4;</code>
         */
        public int getProviderIDCount() {
            return providerID_.size();
        }
        /**
         * <code>repeated int64 providerID = 4;</code>
         */
        public long getProviderID(int index) {
            return providerID_.getLong(index);
        }
        private int providerIDMemoizedSerializedSize = -1;
        private void ensureProviderIDIsMutable() {
            if (!providerID_.isModifiable()) {
                providerID_ =
                        com.google.protobuf.GeneratedMessageLite.mutableCopy(providerID_);
            }
        }
        /**
         * <code>repeated int64 providerID = 4;</code>
         */
        private void setProviderID(
                int index, long value) {
            ensureProviderIDIsMutable();
            providerID_.setLong(index, value);
        }
        /**
         * <code>repeated int64 providerID = 4;</code>
         */
        private void addProviderID(long value) {
            ensureProviderIDIsMutable();
            providerID_.addLong(value);
        }
        /**
         * <code>repeated int64 providerID = 4;</code>
         */
        private void addAllProviderID(
                java.lang.Iterable<? extends java.lang.Long> values) {
            ensureProviderIDIsMutable();
            com.google.protobuf.AbstractMessageLite.addAll(
                    values, providerID_);
        }
        /**
         * <code>repeated int64 providerID = 4;</code>
         */
        private void clearProviderID() {
            providerID_ = emptyLongList();
        }

        public static final int OPCODE_FIELD_NUMBER = 5;
        private com.google.protobuf.Internal.IntList opcode_;
        /**
         * <code>repeated uint32 opcode = 5;</code>
         */
        public java.util.List<java.lang.Integer>
        getOpcodeList() {
            return opcode_;
        }
        /**
         * <code>repeated uint32 opcode = 5;</code>
         */
        public int getOpcodeCount() {
            return opcode_.size();
        }
        /**
         * <code>repeated uint32 opcode = 5;</code>
         */
        public int getOpcode(int index) {
            return opcode_.getInt(index);
        }
        private int opcodeMemoizedSerializedSize = -1;
        private void ensureOpcodeIsMutable() {
            if (!opcode_.isModifiable()) {
                opcode_ =
                        com.google.protobuf.GeneratedMessageLite.mutableCopy(opcode_);
            }
        }
        /**
         * <code>repeated uint32 opcode = 5;</code>
         */
        private void setOpcode(
                int index, int value) {
            ensureOpcodeIsMutable();
            opcode_.setInt(index, value);
        }
        /**
         * <code>repeated uint32 opcode = 5;</code>
         */
        private void addOpcode(int value) {
            ensureOpcodeIsMutable();
            opcode_.addInt(value);
        }
        /**
         * <code>repeated uint32 opcode = 5;</code>
         */
        private void addAllOpcode(
                java.lang.Iterable<? extends java.lang.Integer> values) {
            ensureOpcodeIsMutable();
            com.google.protobuf.AbstractMessageLite.addAll(
                    values, opcode_);
        }
        /**
         * <code>repeated uint32 opcode = 5;</code>
         */
        private void clearOpcode() {
            opcode_ = emptyIntList();
        }

        public static final int PROCESSID_FIELD_NUMBER = 6;
        private com.google.protobuf.Internal.IntList processID_;
        /**
         * <code>repeated int32 processID = 6;</code>
         */
        public java.util.List<java.lang.Integer>
        getProcessIDList() {
            return processID_;
        }
        /**
         * <code>repeated int32 processID = 6;</code>
         */
        public int getProcessIDCount() {
            return processID_.size();
        }
        /**
         * <code>repeated int32 processID = 6;</code>
         */
        public int getProcessID(int index) {
            return processID_.getInt(index);
        }
        private int processIDMemoizedSerializedSize = -1;
        private void ensureProcessIDIsMutable() {
            if (!processID_.isModifiable()) {
                processID_ =
                        com.google.protobuf.GeneratedMessageLite.mutableCopy(processID_);
            }
        }
        /**
         * <code>repeated int32 processID = 6;</code>
         */
        private void setProcessID(
                int index, int value) {
            ensureProcessIDIsMutable();
            processID_.setInt(index, value);
        }
        /**
         * <code>repeated int32 processID = 6;</code>
         */
        private void addProcessID(int value) {
            ensureProcessIDIsMutable();
            processID_.addInt(value);
        }
        /**
         * <code>repeated int32 processID = 6;</code>
         */
        private void addAllProcessID(
                java.lang.Iterable<? extends java.lang.Integer> values) {
            ensureProcessIDIsMutable();
            com.google.protobuf.AbstractMessageLite.addAll(
                    values, processID_);
        }
        /**
         * <code>repeated int32 processID = 6;</code>
         */
        private void clearProcessID() {
            processID_ = emptyIntList();
        }

        public static final int THREADID_FIELD_NUMBER = 7;
        private com.google.protobuf.Internal.IntList threadID_;
        /**
         * <code>repeated int32 threadID = 7;</code>
         */
        public java.util.List<java.lang.Integer>
        getThreadIDList() {
            return threadID_;
        }
        /**
         * <code>repeated int32 threadID = 7;</code>
         */
        public int getThreadIDCount() {
            return threadID_.size();
        }
        /**
         * <code>repeated int32 threadID = 7;</code>
         */
        public int getThreadID(int index) {
            return threadID_.getInt(index);
        }
        private int threadIDMemoizedSerializedSize = -1;
        private void ensureThreadIDIsMutable() {
            if (!threadID_.isModifiable()) {
                threadID_ =
                        com.google.protobuf.GeneratedMessageLite.mutableCopy(threadID_);
            }
        }
        /**
         * <code>repeated int32 threadID = 7;</code>
         */
        private void setThreadID(
                int index, int value) {
            ensureThreadIDIsMutable();
            threadID_.setInt(index, value);
        }
        /**
         * <code>repeated int32 threadID = 7;</code>
         */
        private void addThreadID(int value) {
            ensureThreadIDIsMutable();
            threadID_.addInt(value);
        }
        /**
         * <code>repeated int32 threadID = 7;</code>
         */
        private void addAllThreadID(
                java.lang.Iterable<? extends java.lang.Integer> values) {
            ensureThreadIDIsMutable();
            com.google.protobuf.AbstractMessageLite.addAll(
                    values, threadID_);
        }
        /**
         * <code>repeated int32 threadID = 7;</code>
         */
        private void clearThreadID() {
            threadID_ = emptyIntList();
        }

        public static final int EVENTNAME_FIELD_NUMBER = 8;
        private com.google.protobuf.Internal.ProtobufList<com.google.protobuf.ByteString> eventName_;
        /**
         * <code>repeated bytes eventName = 8;</code>
         */
        public java.util.List<com.google.protobuf.ByteString>
        getEventNameList() {
            return eventName_;
        }
        /**
         * <code>repeated bytes eventName = 8;</code>
         */
        public int getEventNameCount() {
            return eventName_.size();
        }
        /**
         * <code>repeated bytes eventName = 8;</code>
         */
        public com.google.protobuf.ByteString getEventName(int index) {
            return eventName_.get(index);
        }
        private void ensureEventNameIsMutable() {
            if (!eventName_.isModifiable()) {
                eventName_ =
                        com.google.protobuf.GeneratedMessageLite.mutableCopy(eventName_);
            }
        }
        /**
         * <code>repeated bytes eventName = 8;</code>
         */
        private void setEventName(
                int index, com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            ensureEventNameIsMutable();
            eventName_.set(index, value);
        }
        /**
         * <code>repeated bytes eventName = 8;</code>
         */
        private void addEventName(com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            ensureEventNameIsMutable();
            eventName_.add(value);
        }
        /**
         * <code>repeated bytes eventName = 8;</code>
         */
        private void addAllEventName(
                java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
            ensureEventNameIsMutable();
            com.google.protobuf.AbstractMessageLite.addAll(
                    values, eventName_);
        }
        /**
         * <code>repeated bytes eventName = 8;</code>
         */
        private void clearEventName() {
            eventName_ = emptyProtobufList();
        }

        public static final int TIMESTAMP_FIELD_NUMBER = 9;
        private com.google.protobuf.Internal.LongList timestamp_;
        /**
         * <code>repeated int64 timestamp = 9;</code>
         */
        public java.util.List<java.lang.Long>
        getTimestampList() {
            return timestamp_;
        }
        /**
         * <code>repeated int64 timestamp = 9;</code>
         */
        public int getTimestampCount() {
            return timestamp_.size();
        }
        /**
         * <code>repeated int64 timestamp = 9;</code>
         */
        public long getTimestamp(int index) {
            return timestamp_.getLong(index);
        }
        private int timestampMemoizedSerializedSize = -1;
        private void ensureTimestampIsMutable() {
            if (!timestamp_.isModifiable()) {
                timestamp_ =
                        com.google.protobuf.GeneratedMessageLite.mutableCopy(timestamp_);
            }
        }
        /**
         * <code>repeated int64 timestamp = 9;</code>
         */
        private void setTimestamp(
                int index, long value) {
            ensureTimestampIsMutable();
            timestamp_.setLong(index, value);
        }
        /**
         * <code>repeated int64 timestamp = 9;</code>
         */
        private void addTimestamp(long value) {
            ensureTimestampIsMutable();
            timestamp_.addLong(value);
        }
        /**
         * <code>repeated int64 timestamp = 9;</code>
         */
        private void addAllTimestamp(
                java.lang.Iterable<? extends java.lang.Long> values) {
            ensureTimestampIsMutable();
            com.google.protobuf.AbstractMessageLite.addAll(
                    values, timestamp_);
        }
        /**
         * <code>repeated int64 timestamp = 9;</code>
         */
        private void clearTimestamp() {
            timestamp_ = emptyLongList();
        }

        public static final int CALLSTACK_FIELD_NUMBER = 10;
        private com.google.protobuf.Internal.ProtobufList<com.google.protobuf.ByteString> callstack_;
        /**
         * <code>repeated bytes callstack = 10;</code>
         */
        public java.util.List<com.google.protobuf.ByteString>
        getCallstackList() {
            return callstack_;
        }
        /**
         * <code>repeated bytes callstack = 10;</code>
         */
        public int getCallstackCount() {
            return callstack_.size();
        }
        /**
         * <code>repeated bytes callstack = 10;</code>
         */
        public com.google.protobuf.ByteString getCallstack(int index) {
            return callstack_.get(index);
        }
        private void ensureCallstackIsMutable() {
            if (!callstack_.isModifiable()) {
                callstack_ =
                        com.google.protobuf.GeneratedMessageLite.mutableCopy(callstack_);
            }
        }
        /**
         * <code>repeated bytes callstack = 10;</code>
         */
        private void setCallstack(
                int index, com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            ensureCallstackIsMutable();
            callstack_.set(index, value);
        }
        /**
         * <code>repeated bytes callstack = 10;</code>
         */
        private void addCallstack(com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            ensureCallstackIsMutable();
            callstack_.add(value);
        }
        /**
         * <code>repeated bytes callstack = 10;</code>
         */
        private void addAllCallstack(
                java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
            ensureCallstackIsMutable();
            com.google.protobuf.AbstractMessageLite.addAll(
                    values, callstack_);
        }
        /**
         * <code>repeated bytes callstack = 10;</code>
         */
        private void clearCallstack() {
            callstack_ = emptyProtobufList();
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            getSerializedSize();
            for (int i = 0; i < data_.size(); i++) {
                output.writeMessage(1, data_.get(i));
            }
            if (getProviderIDList().size() > 0) {
                output.writeUInt32NoTag(34);
                output.writeUInt32NoTag(providerIDMemoizedSerializedSize);
            }
            for (int i = 0; i < providerID_.size(); i++) {
                output.writeInt64NoTag(providerID_.getLong(i));
            }
            if (getOpcodeList().size() > 0) {
                output.writeUInt32NoTag(42);
                output.writeUInt32NoTag(opcodeMemoizedSerializedSize);
            }
            for (int i = 0; i < opcode_.size(); i++) {
                output.writeUInt32NoTag(opcode_.getInt(i));
            }
            if (getProcessIDList().size() > 0) {
                output.writeUInt32NoTag(50);
                output.writeUInt32NoTag(processIDMemoizedSerializedSize);
            }
            for (int i = 0; i < processID_.size(); i++) {
                output.writeInt32NoTag(processID_.getInt(i));
            }
            if (getThreadIDList().size() > 0) {
                output.writeUInt32NoTag(58);
                output.writeUInt32NoTag(threadIDMemoizedSerializedSize);
            }
            for (int i = 0; i < threadID_.size(); i++) {
                output.writeInt32NoTag(threadID_.getInt(i));
            }
            for (int i = 0; i < eventName_.size(); i++) {
                output.writeBytes(8, eventName_.get(i));
            }
            if (getTimestampList().size() > 0) {
                output.writeUInt32NoTag(74);
                output.writeUInt32NoTag(timestampMemoizedSerializedSize);
            }
            for (int i = 0; i < timestamp_.size(); i++) {
                output.writeInt64NoTag(timestamp_.getLong(i));
            }
            for (int i = 0; i < callstack_.size(); i++) {
                output.writeBytes(10, callstack_.get(i));
            }
            unknownFields.writeTo(output);
        }

        public int getSerializedSize() {
            int size = memoizedSerializedSize;
            if (size != -1) return size;

            size = 0;
            for (int i = 0; i < data_.size(); i++) {
                size += com.google.protobuf.CodedOutputStream
                        .computeMessageSize(1, data_.get(i));
            }
            {
                int dataSize = 0;
                for (int i = 0; i < providerID_.size(); i++) {
                    dataSize += com.google.protobuf.CodedOutputStream
                            .computeInt64SizeNoTag(providerID_.getLong(i));
                }
                size += dataSize;
                if (!getProviderIDList().isEmpty()) {
                    size += 1;
                    size += com.google.protobuf.CodedOutputStream
                            .computeInt32SizeNoTag(dataSize);
                }
                providerIDMemoizedSerializedSize = dataSize;
            }
            {
                int dataSize = 0;
                for (int i = 0; i < opcode_.size(); i++) {
                    dataSize += com.google.protobuf.CodedOutputStream
                            .computeUInt32SizeNoTag(opcode_.getInt(i));
                }
                size += dataSize;
                if (!getOpcodeList().isEmpty()) {
                    size += 1;
                    size += com.google.protobuf.CodedOutputStream
                            .computeInt32SizeNoTag(dataSize);
                }
                opcodeMemoizedSerializedSize = dataSize;
            }
            {
                int dataSize = 0;
                for (int i = 0; i < processID_.size(); i++) {
                    dataSize += com.google.protobuf.CodedOutputStream
                            .computeInt32SizeNoTag(processID_.getInt(i));
                }
                size += dataSize;
                if (!getProcessIDList().isEmpty()) {
                    size += 1;
                    size += com.google.protobuf.CodedOutputStream
                            .computeInt32SizeNoTag(dataSize);
                }
                processIDMemoizedSerializedSize = dataSize;
            }
            {
                int dataSize = 0;
                for (int i = 0; i < threadID_.size(); i++) {
                    dataSize += com.google.protobuf.CodedOutputStream
                            .computeInt32SizeNoTag(threadID_.getInt(i));
                }
                size += dataSize;
                if (!getThreadIDList().isEmpty()) {
                    size += 1;
                    size += com.google.protobuf.CodedOutputStream
                            .computeInt32SizeNoTag(dataSize);
                }
                threadIDMemoizedSerializedSize = dataSize;
            }
            {
                int dataSize = 0;
                for (int i = 0; i < eventName_.size(); i++) {
                    dataSize += com.google.protobuf.CodedOutputStream
                            .computeBytesSizeNoTag(eventName_.get(i));
                }
                size += dataSize;
                size += 1 * getEventNameList().size();
            }
            {
                int dataSize = 0;
                for (int i = 0; i < timestamp_.size(); i++) {
                    dataSize += com.google.protobuf.CodedOutputStream
                            .computeInt64SizeNoTag(timestamp_.getLong(i));
                }
                size += dataSize;
                if (!getTimestampList().isEmpty()) {
                    size += 1;
                    size += com.google.protobuf.CodedOutputStream
                            .computeInt32SizeNoTag(dataSize);
                }
                timestampMemoizedSerializedSize = dataSize;
            }
            {
                int dataSize = 0;
                for (int i = 0; i < callstack_.size(); i++) {
                    dataSize += com.google.protobuf.CodedOutputStream
                            .computeBytesSizeNoTag(callstack_.get(i));
                }
                size += dataSize;
                size += 1 * getCallstackList().size();
            }
            size += unknownFields.getSerializedSize();
            memoizedSerializedSize = size;
            return size;
        }

        public static Etwdata.EventRecords parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                    DEFAULT_INSTANCE, data);
        }
        public static Etwdata.EventRecords parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                    DEFAULT_INSTANCE, data, extensionRegistry);
        }
        public static Etwdata.EventRecords parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                    DEFAULT_INSTANCE, data);
        }
        public static Etwdata.EventRecords parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                    DEFAULT_INSTANCE, data, extensionRegistry);
        }
        public static Etwdata.EventRecords parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                    DEFAULT_INSTANCE, data);
        }
        public static Etwdata.EventRecords parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                    DEFAULT_INSTANCE, data, extensionRegistry);
        }
        public static Etwdata.EventRecords parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                    DEFAULT_INSTANCE, input);
        }
        public static Etwdata.EventRecords parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                    DEFAULT_INSTANCE, input, extensionRegistry);
        }
        public static Etwdata.EventRecords parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return parseDelimitedFrom(DEFAULT_INSTANCE, input);
        }
        public static Etwdata.EventRecords parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
        }
        public static Etwdata.EventRecords parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                    DEFAULT_INSTANCE, input);
        }
        public static Etwdata.EventRecords parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                    DEFAULT_INSTANCE, input, extensionRegistry);
        }

        public static Builder newBuilder() {
            return (Builder) DEFAULT_INSTANCE.createBuilder();
        }
        public static Builder newBuilder(Etwdata.EventRecords prototype) {
            return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
        }

        /**
         * Protobuf type {@code ETWproto.EventRecords}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageLite.Builder<
                        Etwdata.EventRecords, Builder> implements
                // @@protoc_insertion_point(builder_implements:ETWproto.EventRecords)
                Etwdata.EventRecordsOrBuilder {
            // Construct using Etwdata.EventRecords.newBuilder()
            private Builder() {
                super(DEFAULT_INSTANCE);
            }


            /**
             * <code>repeated .ETWproto.datad data = 1;</code>
             */
            public java.util.List<Etwdata.datad> getDataList() {
                return java.util.Collections.unmodifiableList(
                        instance.getDataList());
            }
            /**
             * <code>repeated .ETWproto.datad data = 1;</code>
             */
            public int getDataCount() {
                return instance.getDataCount();
            }/**
             * <code>repeated .ETWproto.datad data = 1;</code>
             */
            public Etwdata.datad getData(int index) {
                return instance.getData(index);
            }
            /**
             * <code>repeated .ETWproto.datad data = 1;</code>
             */
            public Builder setData(
                    int index, Etwdata.datad value) {
                copyOnWrite();
                instance.setData(index, value);
                return this;
            }
            /**
             * <code>repeated .ETWproto.datad data = 1;</code>
             */
            public Builder setData(
                    int index, Etwdata.datad.Builder builderForValue) {
                copyOnWrite();
                instance.setData(index, builderForValue);
                return this;
            }
            /**
             * <code>repeated .ETWproto.datad data = 1;</code>
             */
            public Builder addData(Etwdata.datad value) {
                copyOnWrite();
                instance.addData(value);
                return this;
            }
            /**
             * <code>repeated .ETWproto.datad data = 1;</code>
             */
            public Builder addData(
                    int index, Etwdata.datad value) {
                copyOnWrite();
                instance.addData(index, value);
                return this;
            }
            /**
             * <code>repeated .ETWproto.datad data = 1;</code>
             */
            public Builder addData(
                    Etwdata.datad.Builder builderForValue) {
                copyOnWrite();
                instance.addData(builderForValue);
                return this;
            }
            /**
             * <code>repeated .ETWproto.datad data = 1;</code>
             */
            public Builder addData(
                    int index, Etwdata.datad.Builder builderForValue) {
                copyOnWrite();
                instance.addData(index, builderForValue);
                return this;
            }
            /**
             * <code>repeated .ETWproto.datad data = 1;</code>
             */
            public Builder addAllData(
                    java.lang.Iterable<? extends Etwdata.datad> values) {
                copyOnWrite();
                instance.addAllData(values);
                return this;
            }
            /**
             * <code>repeated .ETWproto.datad data = 1;</code>
             */
            public Builder clearData() {
                copyOnWrite();
                instance.clearData();
                return this;
            }
            /**
             * <code>repeated .ETWproto.datad data = 1;</code>
             */
            public Builder removeData(int index) {
                copyOnWrite();
                instance.removeData(index);
                return this;
            }

            /**
             * <code>repeated int64 providerID = 4;</code>
             */
            public java.util.List<java.lang.Long>
            getProviderIDList() {
                return java.util.Collections.unmodifiableList(
                        instance.getProviderIDList());
            }
            /**
             * <code>repeated int64 providerID = 4;</code>
             */
            public int getProviderIDCount() {
                return instance.getProviderIDCount();
            }
            /**
             * <code>repeated int64 providerID = 4;</code>
             */
            public long getProviderID(int index) {
                return instance.getProviderID(index);
            }
            /**
             * <code>repeated int64 providerID = 4;</code>
             */
            public Builder setProviderID(
                    int index, long value) {
                copyOnWrite();
                instance.setProviderID(index, value);
                return this;
            }
            /**
             * <code>repeated int64 providerID = 4;</code>
             */
            public Builder addProviderID(long value) {
                copyOnWrite();
                instance.addProviderID(value);
                return this;
            }
            /**
             * <code>repeated int64 providerID = 4;</code>
             */
            public Builder addAllProviderID(
                    java.lang.Iterable<? extends java.lang.Long> values) {
                copyOnWrite();
                instance.addAllProviderID(values);
                return this;
            }
            /**
             * <code>repeated int64 providerID = 4;</code>
             */
            public Builder clearProviderID() {
                copyOnWrite();
                instance.clearProviderID();
                return this;
            }

            /**
             * <code>repeated uint32 opcode = 5;</code>
             */
            public java.util.List<java.lang.Integer>
            getOpcodeList() {
                return java.util.Collections.unmodifiableList(
                        instance.getOpcodeList());
            }
            /**
             * <code>repeated uint32 opcode = 5;</code>
             */
            public int getOpcodeCount() {
                return instance.getOpcodeCount();
            }
            /**
             * <code>repeated uint32 opcode = 5;</code>
             */
            public int getOpcode(int index) {
                return instance.getOpcode(index);
            }
            /**
             * <code>repeated uint32 opcode = 5;</code>
             */
            public Builder setOpcode(
                    int index, int value) {
                copyOnWrite();
                instance.setOpcode(index, value);
                return this;
            }
            /**
             * <code>repeated uint32 opcode = 5;</code>
             */
            public Builder addOpcode(int value) {
                copyOnWrite();
                instance.addOpcode(value);
                return this;
            }
            /**
             * <code>repeated uint32 opcode = 5;</code>
             */
            public Builder addAllOpcode(
                    java.lang.Iterable<? extends java.lang.Integer> values) {
                copyOnWrite();
                instance.addAllOpcode(values);
                return this;
            }
            /**
             * <code>repeated uint32 opcode = 5;</code>
             */
            public Builder clearOpcode() {
                copyOnWrite();
                instance.clearOpcode();
                return this;
            }

            /**
             * <code>repeated int32 processID = 6;</code>
             */
            public java.util.List<java.lang.Integer>
            getProcessIDList() {
                return java.util.Collections.unmodifiableList(
                        instance.getProcessIDList());
            }
            /**
             * <code>repeated int32 processID = 6;</code>
             */
            public int getProcessIDCount() {
                return instance.getProcessIDCount();
            }
            /**
             * <code>repeated int32 processID = 6;</code>
             */
            public int getProcessID(int index) {
                return instance.getProcessID(index);
            }
            /**
             * <code>repeated int32 processID = 6;</code>
             */
            public Builder setProcessID(
                    int index, int value) {
                copyOnWrite();
                instance.setProcessID(index, value);
                return this;
            }
            /**
             * <code>repeated int32 processID = 6;</code>
             */
            public Builder addProcessID(int value) {
                copyOnWrite();
                instance.addProcessID(value);
                return this;
            }
            /**
             * <code>repeated int32 processID = 6;</code>
             */
            public Builder addAllProcessID(
                    java.lang.Iterable<? extends java.lang.Integer> values) {
                copyOnWrite();
                instance.addAllProcessID(values);
                return this;
            }
            /**
             * <code>repeated int32 processID = 6;</code>
             */
            public Builder clearProcessID() {
                copyOnWrite();
                instance.clearProcessID();
                return this;
            }

            /**
             * <code>repeated int32 threadID = 7;</code>
             */
            public java.util.List<java.lang.Integer>
            getThreadIDList() {
                return java.util.Collections.unmodifiableList(
                        instance.getThreadIDList());
            }
            /**
             * <code>repeated int32 threadID = 7;</code>
             */
            public int getThreadIDCount() {
                return instance.getThreadIDCount();
            }
            /**
             * <code>repeated int32 threadID = 7;</code>
             */
            public int getThreadID(int index) {
                return instance.getThreadID(index);
            }
            /**
             * <code>repeated int32 threadID = 7;</code>
             */
            public Builder setThreadID(
                    int index, int value) {
                copyOnWrite();
                instance.setThreadID(index, value);
                return this;
            }
            /**
             * <code>repeated int32 threadID = 7;</code>
             */
            public Builder addThreadID(int value) {
                copyOnWrite();
                instance.addThreadID(value);
                return this;
            }
            /**
             * <code>repeated int32 threadID = 7;</code>
             */
            public Builder addAllThreadID(
                    java.lang.Iterable<? extends java.lang.Integer> values) {
                copyOnWrite();
                instance.addAllThreadID(values);
                return this;
            }
            /**
             * <code>repeated int32 threadID = 7;</code>
             */
            public Builder clearThreadID() {
                copyOnWrite();
                instance.clearThreadID();
                return this;
            }

            /**
             * <code>repeated bytes eventName = 8;</code>
             */
            public java.util.List<com.google.protobuf.ByteString>
            getEventNameList() {
                return java.util.Collections.unmodifiableList(
                        instance.getEventNameList());
            }
            /**
             * <code>repeated bytes eventName = 8;</code>
             */
            public int getEventNameCount() {
                return instance.getEventNameCount();
            }
            /**
             * <code>repeated bytes eventName = 8;</code>
             */
            public com.google.protobuf.ByteString getEventName(int index) {
                return instance.getEventName(index);
            }
            /**
             * <code>repeated bytes eventName = 8;</code>
             */
            public Builder setEventName(
                    int index, com.google.protobuf.ByteString value) {
                copyOnWrite();
                instance.setEventName(index, value);
                return this;
            }
            /**
             * <code>repeated bytes eventName = 8;</code>
             */
            public Builder addEventName(com.google.protobuf.ByteString value) {
                copyOnWrite();
                instance.addEventName(value);
                return this;
            }
            /**
             * <code>repeated bytes eventName = 8;</code>
             */
            public Builder addAllEventName(
                    java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
                copyOnWrite();
                instance.addAllEventName(values);
                return this;
            }
            /**
             * <code>repeated bytes eventName = 8;</code>
             */
            public Builder clearEventName() {
                copyOnWrite();
                instance.clearEventName();
                return this;
            }

            /**
             * <code>repeated int64 timestamp = 9;</code>
             */
            public java.util.List<java.lang.Long>
            getTimestampList() {
                return java.util.Collections.unmodifiableList(
                        instance.getTimestampList());
            }
            /**
             * <code>repeated int64 timestamp = 9;</code>
             */
            public int getTimestampCount() {
                return instance.getTimestampCount();
            }
            /**
             * <code>repeated int64 timestamp = 9;</code>
             */
            public long getTimestamp(int index) {
                return instance.getTimestamp(index);
            }
            /**
             * <code>repeated int64 timestamp = 9;</code>
             */
            public Builder setTimestamp(
                    int index, long value) {
                copyOnWrite();
                instance.setTimestamp(index, value);
                return this;
            }
            /**
             * <code>repeated int64 timestamp = 9;</code>
             */
            public Builder addTimestamp(long value) {
                copyOnWrite();
                instance.addTimestamp(value);
                return this;
            }
            /**
             * <code>repeated int64 timestamp = 9;</code>
             */
            public Builder addAllTimestamp(
                    java.lang.Iterable<? extends java.lang.Long> values) {
                copyOnWrite();
                instance.addAllTimestamp(values);
                return this;
            }
            /**
             * <code>repeated int64 timestamp = 9;</code>
             */
            public Builder clearTimestamp() {
                copyOnWrite();
                instance.clearTimestamp();
                return this;
            }

            /**
             * <code>repeated bytes callstack = 10;</code>
             */
            public java.util.List<com.google.protobuf.ByteString>
            getCallstackList() {
                return java.util.Collections.unmodifiableList(
                        instance.getCallstackList());
            }
            /**
             * <code>repeated bytes callstack = 10;</code>
             */
            public int getCallstackCount() {
                return instance.getCallstackCount();
            }
            /**
             * <code>repeated bytes callstack = 10;</code>
             */
            public com.google.protobuf.ByteString getCallstack(int index) {
                return instance.getCallstack(index);
            }
            /**
             * <code>repeated bytes callstack = 10;</code>
             */
            public Builder setCallstack(
                    int index, com.google.protobuf.ByteString value) {
                copyOnWrite();
                instance.setCallstack(index, value);
                return this;
            }
            /**
             * <code>repeated bytes callstack = 10;</code>
             */
            public Builder addCallstack(com.google.protobuf.ByteString value) {
                copyOnWrite();
                instance.addCallstack(value);
                return this;
            }
            /**
             * <code>repeated bytes callstack = 10;</code>
             */
            public Builder addAllCallstack(
                    java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
                copyOnWrite();
                instance.addAllCallstack(values);
                return this;
            }
            /**
             * <code>repeated bytes callstack = 10;</code>
             */
            public Builder clearCallstack() {
                copyOnWrite();
                instance.clearCallstack();
                return this;
            }

            // @@protoc_insertion_point(builder_scope:ETWproto.EventRecords)
        }
        @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
        protected final java.lang.Object dynamicMethod(
                com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
                java.lang.Object arg0, java.lang.Object arg1) {
            switch (method) {
                case NEW_MUTABLE_INSTANCE: {
                    return new Etwdata.EventRecords();
                }
                case IS_INITIALIZED: {
                    return DEFAULT_INSTANCE;
                }
                case MAKE_IMMUTABLE: {
                    data_.makeImmutable();
                    providerID_.makeImmutable();
                    opcode_.makeImmutable();
                    processID_.makeImmutable();
                    threadID_.makeImmutable();
                    eventName_.makeImmutable();
                    timestamp_.makeImmutable();
                    callstack_.makeImmutable();
                    return null;
                }
                case NEW_BUILDER: {
                    return new Builder();
                }
                case VISIT: {
                    Visitor visitor = (Visitor) arg0;
                    Etwdata.EventRecords other = (Etwdata.EventRecords) arg1;
                    data_= visitor.visitList(data_, other.data_);
                    providerID_= visitor.visitLongList(providerID_, other.providerID_);
                    opcode_= visitor.visitIntList(opcode_, other.opcode_);
                    processID_= visitor.visitIntList(processID_, other.processID_);
                    threadID_= visitor.visitIntList(threadID_, other.threadID_);
                    eventName_= visitor.visitList(eventName_, other.eventName_);
                    timestamp_= visitor.visitLongList(timestamp_, other.timestamp_);
                    callstack_= visitor.visitList(callstack_, other.callstack_);
                    if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
                            .INSTANCE) {
                    }
                    return this;
                }
                case MERGE_FROM_STREAM: {
                    com.google.protobuf.CodedInputStream input =
                            (com.google.protobuf.CodedInputStream) arg0;
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry =
                            (com.google.protobuf.ExtensionRegistryLite) arg1;
                    if (extensionRegistry == null) {
                        throw new java.lang.NullPointerException();
                    }
                    try {
                        boolean done = false;
                        while (!done) {
                            int tag = input.readTag();
                            switch (tag) {
                                case 0:
                                    done = true;
                                    break;
                                default: {
                                    if (!parseUnknownField(tag, input)) {
                                        done = true;
                                    }
                                    break;
                                }
                                case 10: {
                                    if (!data_.isModifiable()) {
                                        data_ =
                                                com.google.protobuf.GeneratedMessageLite.mutableCopy(data_);
                                    }
                                    data_.add(
                                            input.readMessage(Etwdata.datad.parser(), extensionRegistry));
                                    break;
                                }
                                case 32: {
                                    if (!providerID_.isModifiable()) {
                                        providerID_ =
                                                com.google.protobuf.GeneratedMessageLite.mutableCopy(providerID_);
                                    }
                                    providerID_.addLong(input.readInt64());
                                    break;
                                }
                                case 34: {
                                    int length = input.readRawVarint32();
                                    int limit = input.pushLimit(length);
                                    if (!providerID_.isModifiable() && input.getBytesUntilLimit() > 0) {
                                        providerID_ =
                                                com.google.protobuf.GeneratedMessageLite.mutableCopy(providerID_);
                                    }
                                    while (input.getBytesUntilLimit() > 0) {
                                        providerID_.addLong(input.readInt64());
                                    }
                                    input.popLimit(limit);
                                    break;
                                }
                                case 40: {
                                    if (!opcode_.isModifiable()) {
                                        opcode_ =
                                                com.google.protobuf.GeneratedMessageLite.mutableCopy(opcode_);
                                    }
                                    opcode_.addInt(input.readUInt32());
                                    break;
                                }
                                case 42: {
                                    int length = input.readRawVarint32();
                                    int limit = input.pushLimit(length);
                                    if (!opcode_.isModifiable() && input.getBytesUntilLimit() > 0) {
                                        opcode_ =
                                                com.google.protobuf.GeneratedMessageLite.mutableCopy(opcode_);
                                    }
                                    while (input.getBytesUntilLimit() > 0) {
                                        opcode_.addInt(input.readUInt32());
                                    }
                                    input.popLimit(limit);
                                    break;
                                }
                                case 48: {
                                    if (!processID_.isModifiable()) {
                                        processID_ =
                                                com.google.protobuf.GeneratedMessageLite.mutableCopy(processID_);
                                    }
                                    processID_.addInt(input.readInt32());
                                    break;
                                }
                                case 50: {
                                    int length = input.readRawVarint32();
                                    int limit = input.pushLimit(length);
                                    if (!processID_.isModifiable() && input.getBytesUntilLimit() > 0) {
                                        processID_ =
                                                com.google.protobuf.GeneratedMessageLite.mutableCopy(processID_);
                                    }
                                    while (input.getBytesUntilLimit() > 0) {
                                        processID_.addInt(input.readInt32());
                                    }
                                    input.popLimit(limit);
                                    break;
                                }
                                case 56: {
                                    if (!threadID_.isModifiable()) {
                                        threadID_ =
                                                com.google.protobuf.GeneratedMessageLite.mutableCopy(threadID_);
                                    }
                                    threadID_.addInt(input.readInt32());
                                    break;
                                }
                                case 58: {
                                    int length = input.readRawVarint32();
                                    int limit = input.pushLimit(length);
                                    if (!threadID_.isModifiable() && input.getBytesUntilLimit() > 0) {
                                        threadID_ =
                                                com.google.protobuf.GeneratedMessageLite.mutableCopy(threadID_);
                                    }
                                    while (input.getBytesUntilLimit() > 0) {
                                        threadID_.addInt(input.readInt32());
                                    }
                                    input.popLimit(limit);
                                    break;
                                }
                                case 66: {
                                    if (!eventName_.isModifiable()) {
                                        eventName_ =
                                                com.google.protobuf.GeneratedMessageLite.mutableCopy(eventName_);
                                    }
                                    eventName_.add(input.readBytes());
                                    break;
                                }
                                case 72: {
                                    if (!timestamp_.isModifiable()) {
                                        timestamp_ =
                                                com.google.protobuf.GeneratedMessageLite.mutableCopy(timestamp_);
                                    }
                                    timestamp_.addLong(input.readInt64());
                                    break;
                                }
                                case 74: {
                                    int length = input.readRawVarint32();
                                    int limit = input.pushLimit(length);
                                    if (!timestamp_.isModifiable() && input.getBytesUntilLimit() > 0) {
                                        timestamp_ =
                                                com.google.protobuf.GeneratedMessageLite.mutableCopy(timestamp_);
                                    }
                                    while (input.getBytesUntilLimit() > 0) {
                                        timestamp_.addLong(input.readInt64());
                                    }
                                    input.popLimit(limit);
                                    break;
                                }
                                case 82: {
                                    if (!callstack_.isModifiable()) {
                                        callstack_ =
                                                com.google.protobuf.GeneratedMessageLite.mutableCopy(callstack_);
                                    }
                                    callstack_.add(input.readBytes());
                                    break;
                                }
                            }
                        }
                    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                        throw new RuntimeException(e.setUnfinishedMessage(this));
                    } catch (java.io.IOException e) {
                        throw new RuntimeException(
                                new com.google.protobuf.InvalidProtocolBufferException(
                                        e.getMessage()).setUnfinishedMessage(this));
                    } finally {
                    }
                }
                // fall through
                case GET_DEFAULT_INSTANCE: {
                    return DEFAULT_INSTANCE;
                }
                case GET_PARSER: {
                    if (PARSER == null) {    synchronized (Etwdata.EventRecords.class) {
                        if (PARSER == null) {
                            PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
                        }
                    }
                    }
                    return PARSER;
                }
                case GET_MEMOIZED_IS_INITIALIZED: {
                    return (byte) 1;
                }
                case SET_MEMOIZED_IS_INITIALIZED: {
                    return null;
                }
            }
            throw new UnsupportedOperationException();
        }


        // @@protoc_insertion_point(class_scope:ETWproto.EventRecords)
        private static final Etwdata.EventRecords DEFAULT_INSTANCE;
        static {
            DEFAULT_INSTANCE = new EventRecords();
            DEFAULT_INSTANCE.makeImmutable();
        }

        public static Etwdata.EventRecords getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static volatile com.google.protobuf.Parser<EventRecords> PARSER;

        public static com.google.protobuf.Parser<EventRecords> parser() {
            return DEFAULT_INSTANCE.getParserForType();
        }
    }

    public interface datadOrBuilder extends
            // @@protoc_insertion_point(interface_extends:ETWproto.datad)
            com.google.protobuf.MessageLiteOrBuilder {

        /**
         * <code>repeated bytes s = 1;</code>
         */
        java.util.List<com.google.protobuf.ByteString> getSList();
        /**
         * <code>repeated bytes s = 1;</code>
         */
        int getSCount();
        /**
         * <code>repeated bytes s = 1;</code>
         */
        com.google.protobuf.ByteString getS(int index);

        /**
         * <code>repeated int64 d = 2;</code>
         */
        java.util.List<java.lang.Long> getDList();
        /**
         * <code>repeated int64 d = 2;</code>
         */
        int getDCount();
        /**
         * <code>repeated int64 d = 2;</code>
         */
        long getD(int index);
    }
    /**
     * Protobuf type {@code ETWproto.datad}
     */
    public  static final class datad extends
            com.google.protobuf.GeneratedMessageLite<
                    datad, datad.Builder> implements
            // @@protoc_insertion_point(message_implements:ETWproto.datad)
            datadOrBuilder {
        private datad() {
            s_ = emptyProtobufList();
            d_ = emptyLongList();
        }
        public static final int S_FIELD_NUMBER = 1;
        private com.google.protobuf.Internal.ProtobufList<com.google.protobuf.ByteString> s_;
        /**
         * <code>repeated bytes s = 1;</code>
         */
        public java.util.List<com.google.protobuf.ByteString>
        getSList() {
            return s_;
        }
        /**
         * <code>repeated bytes s = 1;</code>
         */
        public int getSCount() {
            return s_.size();
        }
        /**
         * <code>repeated bytes s = 1;</code>
         */
        public com.google.protobuf.ByteString getS(int index) {
            return s_.get(index);
        }
        private void ensureSIsMutable() {
            if (!s_.isModifiable()) {
                s_ =
                        com.google.protobuf.GeneratedMessageLite.mutableCopy(s_);
            }
        }
        /**
         * <code>repeated bytes s = 1;</code>
         */
        private void setS(
                int index, com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            ensureSIsMutable();
            s_.set(index, value);
        }
        /**
         * <code>repeated bytes s = 1;</code>
         */
        private void addS(com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            ensureSIsMutable();
            s_.add(value);
        }
        /**
         * <code>repeated bytes s = 1;</code>
         */
        private void addAllS(
                java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
            ensureSIsMutable();
            com.google.protobuf.AbstractMessageLite.addAll(
                    values, s_);
        }
        /**
         * <code>repeated bytes s = 1;</code>
         */
        private void clearS() {
            s_ = emptyProtobufList();
        }

        public static final int D_FIELD_NUMBER = 2;
        private com.google.protobuf.Internal.LongList d_;
        /**
         * <code>repeated int64 d = 2;</code>
         */
        public java.util.List<java.lang.Long>
        getDList() {
            return d_;
        }
        /**
         * <code>repeated int64 d = 2;</code>
         */
        public int getDCount() {
            return d_.size();
        }
        /**
         * <code>repeated int64 d = 2;</code>
         */
        public long getD(int index) {
            return d_.getLong(index);
        }
        private int dMemoizedSerializedSize = -1;
        private void ensureDIsMutable() {
            if (!d_.isModifiable()) {
                d_ =
                        com.google.protobuf.GeneratedMessageLite.mutableCopy(d_);
            }
        }
        /**
         * <code>repeated int64 d = 2;</code>
         */
        private void setD(
                int index, long value) {
            ensureDIsMutable();
            d_.setLong(index, value);
        }
        /**
         * <code>repeated int64 d = 2;</code>
         */
        private void addD(long value) {
            ensureDIsMutable();
            d_.addLong(value);
        }
        /**
         * <code>repeated int64 d = 2;</code>
         */
        private void addAllD(
                java.lang.Iterable<? extends java.lang.Long> values) {
            ensureDIsMutable();
            com.google.protobuf.AbstractMessageLite.addAll(
                    values, d_);
        }
        /**
         * <code>repeated int64 d = 2;</code>
         */
        private void clearD() {
            d_ = emptyLongList();
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            getSerializedSize();
            for (int i = 0; i < s_.size(); i++) {
                output.writeBytes(1, s_.get(i));
            }
            if (getDList().size() > 0) {
                output.writeUInt32NoTag(18);
                output.writeUInt32NoTag(dMemoizedSerializedSize);
            }
            for (int i = 0; i < d_.size(); i++) {
                output.writeInt64NoTag(d_.getLong(i));
            }
            unknownFields.writeTo(output);
        }

        public int getSerializedSize() {
            int size = memoizedSerializedSize;
            if (size != -1) return size;

            size = 0;
            {
                int dataSize = 0;
                for (int i = 0; i < s_.size(); i++) {
                    dataSize += com.google.protobuf.CodedOutputStream
                            .computeBytesSizeNoTag(s_.get(i));
                }
                size += dataSize;
                size += 1 * getSList().size();
            }
            {
                int dataSize = 0;
                for (int i = 0; i < d_.size(); i++) {
                    dataSize += com.google.protobuf.CodedOutputStream
                            .computeInt64SizeNoTag(d_.getLong(i));
                }
                size += dataSize;
                if (!getDList().isEmpty()) {
                    size += 1;
                    size += com.google.protobuf.CodedOutputStream
                            .computeInt32SizeNoTag(dataSize);
                }
                dMemoizedSerializedSize = dataSize;
            }
            size += unknownFields.getSerializedSize();
            memoizedSerializedSize = size;
            return size;
        }

        public static Etwdata.datad parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                    DEFAULT_INSTANCE, data);
        }
        public static Etwdata.datad parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                    DEFAULT_INSTANCE, data, extensionRegistry);
        }
        public static Etwdata.datad parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                    DEFAULT_INSTANCE, data);
        }
        public static Etwdata.datad parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                    DEFAULT_INSTANCE, data, extensionRegistry);
        }
        public static Etwdata.datad parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                    DEFAULT_INSTANCE, data);
        }
        public static Etwdata.datad parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                    DEFAULT_INSTANCE, data, extensionRegistry);
        }
        public static Etwdata.datad parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                    DEFAULT_INSTANCE, input);
        }
        public static Etwdata.datad parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                    DEFAULT_INSTANCE, input, extensionRegistry);
        }
        public static Etwdata.datad parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return parseDelimitedFrom(DEFAULT_INSTANCE, input);
        }
        public static Etwdata.datad parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
        }
        public static Etwdata.datad parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                    DEFAULT_INSTANCE, input);
        }
        public static Etwdata.datad parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                    DEFAULT_INSTANCE, input, extensionRegistry);
        }

        public static Builder newBuilder() {
            return (Builder) DEFAULT_INSTANCE.createBuilder();
        }
        public static Builder newBuilder(Etwdata.datad prototype) {
            return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
        }

        /**
         * Protobuf type {@code ETWproto.datad}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageLite.Builder<
                        Etwdata.datad, Builder> implements
                // @@protoc_insertion_point(builder_implements:ETWproto.datad)
                Etwdata.datadOrBuilder {
            // Construct using Etwdata.datad.newBuilder()
            private Builder() {
                super(DEFAULT_INSTANCE);
            }


            /**
             * <code>repeated bytes s = 1;</code>
             */
            public java.util.List<com.google.protobuf.ByteString>
            getSList() {
                return java.util.Collections.unmodifiableList(
                        instance.getSList());
            }
            /**
             * <code>repeated bytes s = 1;</code>
             */
            public int getSCount() {
                return instance.getSCount();
            }
            /**
             * <code>repeated bytes s = 1;</code>
             */
            public com.google.protobuf.ByteString getS(int index) {
                return instance.getS(index);
            }
            /**
             * <code>repeated bytes s = 1;</code>
             */
            public Builder setS(
                    int index, com.google.protobuf.ByteString value) {
                copyOnWrite();
                instance.setS(index, value);
                return this;
            }
            /**
             * <code>repeated bytes s = 1;</code>
             */
            public Builder addS(com.google.protobuf.ByteString value) {
                copyOnWrite();
                instance.addS(value);
                return this;
            }
            /**
             * <code>repeated bytes s = 1;</code>
             */
            public Builder addAllS(
                    java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
                copyOnWrite();
                instance.addAllS(values);
                return this;
            }
            /**
             * <code>repeated bytes s = 1;</code>
             */
            public Builder clearS() {
                copyOnWrite();
                instance.clearS();
                return this;
            }

            /**
             * <code>repeated int64 d = 2;</code>
             */
            public java.util.List<java.lang.Long>
            getDList() {
                return java.util.Collections.unmodifiableList(
                        instance.getDList());
            }
            /**
             * <code>repeated int64 d = 2;</code>
             */
            public int getDCount() {
                return instance.getDCount();
            }
            /**
             * <code>repeated int64 d = 2;</code>
             */
            public long getD(int index) {
                return instance.getD(index);
            }
            /**
             * <code>repeated int64 d = 2;</code>
             */
            public Builder setD(
                    int index, long value) {
                copyOnWrite();
                instance.setD(index, value);
                return this;
            }
            /**
             * <code>repeated int64 d = 2;</code>
             */
            public Builder addD(long value) {
                copyOnWrite();
                instance.addD(value);
                return this;
            }
            /**
             * <code>repeated int64 d = 2;</code>
             */
            public Builder addAllD(
                    java.lang.Iterable<? extends java.lang.Long> values) {
                copyOnWrite();
                instance.addAllD(values);
                return this;
            }
            /**
             * <code>repeated int64 d = 2;</code>
             */
            public Builder clearD() {
                copyOnWrite();
                instance.clearD();
                return this;
            }

            // @@protoc_insertion_point(builder_scope:ETWproto.datad)
        }
        @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
        protected final java.lang.Object dynamicMethod(
                com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
                java.lang.Object arg0, java.lang.Object arg1) {
            switch (method) {
                case NEW_MUTABLE_INSTANCE: {
                    return new Etwdata.datad();
                }
                case IS_INITIALIZED: {
                    return DEFAULT_INSTANCE;
                }
                case MAKE_IMMUTABLE: {
                    s_.makeImmutable();
                    d_.makeImmutable();
                    return null;
                }
                case NEW_BUILDER: {
                    return new Builder();
                }
                case VISIT: {
                    Visitor visitor = (Visitor) arg0;
                    Etwdata.datad other = (Etwdata.datad) arg1;
                    s_= visitor.visitList(s_, other.s_);
                    d_= visitor.visitLongList(d_, other.d_);
                    if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
                            .INSTANCE) {
                    }
                    return this;
                }
                case MERGE_FROM_STREAM: {
                    com.google.protobuf.CodedInputStream input =
                            (com.google.protobuf.CodedInputStream) arg0;
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry =
                            (com.google.protobuf.ExtensionRegistryLite) arg1;
                    if (extensionRegistry == null) {
                        throw new java.lang.NullPointerException();
                    }
                    try {
                        boolean done = false;
                        while (!done) {
                            int tag = input.readTag();
                            switch (tag) {
                                case 0:
                                    done = true;
                                    break;
                                default: {
                                    if (!parseUnknownField(tag, input)) {
                                        done = true;
                                    }
                                    break;
                                }
                                case 10: {
                                    if (!s_.isModifiable()) {
                                        s_ =
                                                com.google.protobuf.GeneratedMessageLite.mutableCopy(s_);
                                    }
                                    s_.add(input.readBytes());
                                    break;
                                }
                                case 16: {
                                    if (!d_.isModifiable()) {
                                        d_ =
                                                com.google.protobuf.GeneratedMessageLite.mutableCopy(d_);
                                    }
                                    d_.addLong(input.readInt64());
                                    break;
                                }
                                case 18: {
                                    int length = input.readRawVarint32();
                                    int limit = input.pushLimit(length);
                                    if (!d_.isModifiable() && input.getBytesUntilLimit() > 0) {
                                        d_ =
                                                com.google.protobuf.GeneratedMessageLite.mutableCopy(d_);
                                    }
                                    while (input.getBytesUntilLimit() > 0) {
                                        d_.addLong(input.readInt64());
                                    }
                                    input.popLimit(limit);
                                    break;
                                }
                            }
                        }
                    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                        throw new RuntimeException(e.setUnfinishedMessage(this));
                    } catch (java.io.IOException e) {
                        throw new RuntimeException(
                                new com.google.protobuf.InvalidProtocolBufferException(
                                        e.getMessage()).setUnfinishedMessage(this));
                    } finally {
                    }
                }
                // fall through
                case GET_DEFAULT_INSTANCE: {
                    return DEFAULT_INSTANCE;
                }
                case GET_PARSER: {
                    if (PARSER == null) {    synchronized (Etwdata.datad.class) {
                        if (PARSER == null) {
                            PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
                        }
                    }
                    }
                    return PARSER;
                }
                case GET_MEMOIZED_IS_INITIALIZED: {
                    return (byte) 1;
                }
                case SET_MEMOIZED_IS_INITIALIZED: {
                    return null;
                }
            }
            throw new UnsupportedOperationException();
        }


        // @@protoc_insertion_point(class_scope:ETWproto.datad)
        private static final Etwdata.datad DEFAULT_INSTANCE;
        static {
            DEFAULT_INSTANCE = new datad();
            DEFAULT_INSTANCE.makeImmutable();
        }

        public static Etwdata.datad getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static volatile com.google.protobuf.Parser<datad> PARSER;

        public static com.google.protobuf.Parser<datad> parser() {
            return DEFAULT_INSTANCE.getParserForType();
        }
    }


    static {
    }

    // @@protoc_insertion_point(outer_class_scope)
}
